# ===================================
# Filter Scope Definitions
# ===================================
scopes:
    show_read:
        label: Show Read
        type: checkbox
        scope: disableunread